namespace demo.PL.Accounts
{
    partial class frm_accounts
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frm_accounts));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btn_new = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_Save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_Edit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_delete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.tr_account = new System.Windows.Forms.TreeView();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.txt_acc_debit = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_acc_parent_no = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_acc_balance = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_acc_credit = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_acc_level = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_acc_name = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txt_accNo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cb_AccType = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label3 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.cb_report = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label5 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            this.bunifuShadowPanel3.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.bunifuShadowPanel3);
            this.panel1.Controls.Add(this.bunifuShadowPanel2);
            this.panel1.Controls.Add(this.bunifuShadowPanel1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.panel1.Size = new System.Drawing.Size(858, 684);
            this.panel1.TabIndex = 81;
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.BorderRadius = 1;
            this.bunifuShadowPanel3.BorderThickness = 1;
            this.bunifuShadowPanel3.Controls.Add(this.btn_new);
            this.bunifuShadowPanel3.Controls.Add(this.btn_Save);
            this.bunifuShadowPanel3.Controls.Add(this.btn_Edit);
            this.bunifuShadowPanel3.Controls.Add(this.btn_delete);
            this.bunifuShadowPanel3.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel3.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(12, 548);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowDepth = 5;
            this.bunifuShadowPanel3.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(825, 99);
            this.bunifuShadowPanel3.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel3.TabIndex = 16;
            // 
            // btn_new
            // 
            this.btn_new.AllowAnimations = true;
            this.btn_new.AllowMouseEffects = true;
            this.btn_new.AllowToggling = false;
            this.btn_new.AnimationSpeed = 200;
            this.btn_new.AutoGenerateColors = false;
            this.btn_new.AutoRoundBorders = false;
            this.btn_new.AutoSizeLeftIcon = true;
            this.btn_new.AutoSizeRightIcon = true;
            this.btn_new.BackColor = System.Drawing.Color.Transparent;
            this.btn_new.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_new.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_new.BackgroundImage")));
            this.btn_new.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.ButtonText = "جديد";
            this.btn_new.ButtonTextMarginLeft = 0;
            this.btn_new.ColorContrastOnClick = 45;
            this.btn_new.ColorContrastOnHover = 45;
            this.btn_new.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_new.CustomizableEdges = borderEdges5;
            this.btn_new.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_new.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_new.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_new.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_new.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_new.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.btn_new.ForeColor = System.Drawing.Color.White;
            this.btn_new.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_new.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_new.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_new.IconMarginLeft = 11;
            this.btn_new.IconPadding = 10;
            this.btn_new.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_new.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_new.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_new.IconSize = 25;
            this.btn_new.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_new.IdleBorderRadius = 1;
            this.btn_new.IdleBorderThickness = 1;
            this.btn_new.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_new.IdleIconLeftImage = null;
            this.btn_new.IdleIconRightImage = null;
            this.btn_new.IndicateFocus = false;
            this.btn_new.Location = new System.Drawing.Point(635, 34);
            this.btn_new.Name = "btn_new";
            this.btn_new.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_new.OnDisabledState.BorderRadius = 1;
            this.btn_new.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.OnDisabledState.BorderThickness = 1;
            this.btn_new.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_new.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_new.OnDisabledState.IconLeftImage = null;
            this.btn_new.OnDisabledState.IconRightImage = null;
            this.btn_new.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_new.onHoverState.BorderRadius = 1;
            this.btn_new.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.onHoverState.BorderThickness = 1;
            this.btn_new.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_new.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_new.onHoverState.IconLeftImage = null;
            this.btn_new.onHoverState.IconRightImage = null;
            this.btn_new.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_new.OnIdleState.BorderRadius = 1;
            this.btn_new.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.OnIdleState.BorderThickness = 1;
            this.btn_new.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_new.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_new.OnIdleState.IconLeftImage = null;
            this.btn_new.OnIdleState.IconRightImage = null;
            this.btn_new.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_new.OnPressedState.BorderRadius = 1;
            this.btn_new.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.OnPressedState.BorderThickness = 1;
            this.btn_new.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_new.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_new.OnPressedState.IconLeftImage = null;
            this.btn_new.OnPressedState.IconRightImage = null;
            this.btn_new.Size = new System.Drawing.Size(150, 39);
            this.btn_new.TabIndex = 11;
            this.btn_new.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_new.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_new.TextMarginLeft = 0;
            this.btn_new.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_new.UseDefaultRadiusAndThickness = true;
            this.btn_new.Click += new System.EventHandler(this.btn_new_Click);
            // 
            // btn_Save
            // 
            this.btn_Save.AllowAnimations = true;
            this.btn_Save.AllowMouseEffects = true;
            this.btn_Save.AllowToggling = false;
            this.btn_Save.AnimationSpeed = 200;
            this.btn_Save.AutoGenerateColors = false;
            this.btn_Save.AutoRoundBorders = false;
            this.btn_Save.AutoSizeLeftIcon = true;
            this.btn_Save.AutoSizeRightIcon = true;
            this.btn_Save.BackColor = System.Drawing.Color.Transparent;
            this.btn_Save.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_Save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Save.BackgroundImage")));
            this.btn_Save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.ButtonText = "حفظ";
            this.btn_Save.ButtonTextMarginLeft = 0;
            this.btn_Save.ColorContrastOnClick = 45;
            this.btn_Save.ColorContrastOnHover = 45;
            this.btn_Save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_Save.CustomizableEdges = borderEdges6;
            this.btn_Save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Save.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Save.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Save.Enabled = false;
            this.btn_Save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Save.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Save.ForeColor = System.Drawing.Color.White;
            this.btn_Save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Save.IconMarginLeft = 11;
            this.btn_Save.IconPadding = 10;
            this.btn_Save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Save.IconSize = 25;
            this.btn_Save.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_Save.IdleBorderRadius = 1;
            this.btn_Save.IdleBorderThickness = 1;
            this.btn_Save.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_Save.IdleIconLeftImage = null;
            this.btn_Save.IdleIconRightImage = null;
            this.btn_Save.IndicateFocus = false;
            this.btn_Save.Location = new System.Drawing.Point(429, 34);
            this.btn_Save.Name = "btn_Save";
            this.btn_Save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Save.OnDisabledState.BorderRadius = 1;
            this.btn_Save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.OnDisabledState.BorderThickness = 1;
            this.btn_Save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Save.OnDisabledState.IconLeftImage = null;
            this.btn_Save.OnDisabledState.IconRightImage = null;
            this.btn_Save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Save.onHoverState.BorderRadius = 1;
            this.btn_Save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.onHoverState.BorderThickness = 1;
            this.btn_Save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Save.onHoverState.IconLeftImage = null;
            this.btn_Save.onHoverState.IconRightImage = null;
            this.btn_Save.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_Save.OnIdleState.BorderRadius = 1;
            this.btn_Save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.OnIdleState.BorderThickness = 1;
            this.btn_Save.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_Save.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Save.OnIdleState.IconLeftImage = null;
            this.btn_Save.OnIdleState.IconRightImage = null;
            this.btn_Save.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Save.OnPressedState.BorderRadius = 1;
            this.btn_Save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.OnPressedState.BorderThickness = 1;
            this.btn_Save.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Save.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Save.OnPressedState.IconLeftImage = null;
            this.btn_Save.OnPressedState.IconRightImage = null;
            this.btn_Save.Size = new System.Drawing.Size(150, 39);
            this.btn_Save.TabIndex = 10;
            this.btn_Save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Save.TextMarginLeft = 0;
            this.btn_Save.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_Save.UseDefaultRadiusAndThickness = true;
            this.btn_Save.Click += new System.EventHandler(this.btn_Save_Click);
            // 
            // btn_Edit
            // 
            this.btn_Edit.AllowAnimations = true;
            this.btn_Edit.AllowMouseEffects = true;
            this.btn_Edit.AllowToggling = false;
            this.btn_Edit.AnimationSpeed = 200;
            this.btn_Edit.AutoGenerateColors = false;
            this.btn_Edit.AutoRoundBorders = false;
            this.btn_Edit.AutoSizeLeftIcon = true;
            this.btn_Edit.AutoSizeRightIcon = true;
            this.btn_Edit.BackColor = System.Drawing.Color.Transparent;
            this.btn_Edit.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Edit.BackgroundImage")));
            this.btn_Edit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.ButtonText = "تعديل";
            this.btn_Edit.ButtonTextMarginLeft = 0;
            this.btn_Edit.ColorContrastOnClick = 45;
            this.btn_Edit.ColorContrastOnHover = 45;
            this.btn_Edit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_Edit.CustomizableEdges = borderEdges7;
            this.btn_Edit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Edit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Edit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Edit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Edit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Edit.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Edit.ForeColor = System.Drawing.Color.White;
            this.btn_Edit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Edit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Edit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Edit.IconMarginLeft = 11;
            this.btn_Edit.IconPadding = 10;
            this.btn_Edit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Edit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Edit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Edit.IconSize = 25;
            this.btn_Edit.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.IdleBorderRadius = 1;
            this.btn_Edit.IdleBorderThickness = 1;
            this.btn_Edit.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.IdleIconLeftImage = null;
            this.btn_Edit.IdleIconRightImage = null;
            this.btn_Edit.IndicateFocus = false;
            this.btn_Edit.Location = new System.Drawing.Point(223, 34);
            this.btn_Edit.Name = "btn_Edit";
            this.btn_Edit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Edit.OnDisabledState.BorderRadius = 1;
            this.btn_Edit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.OnDisabledState.BorderThickness = 1;
            this.btn_Edit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Edit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Edit.OnDisabledState.IconLeftImage = null;
            this.btn_Edit.OnDisabledState.IconRightImage = null;
            this.btn_Edit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Edit.onHoverState.BorderRadius = 1;
            this.btn_Edit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.onHoverState.BorderThickness = 1;
            this.btn_Edit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Edit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Edit.onHoverState.IconLeftImage = null;
            this.btn_Edit.onHoverState.IconRightImage = null;
            this.btn_Edit.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.OnIdleState.BorderRadius = 1;
            this.btn_Edit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.OnIdleState.BorderThickness = 1;
            this.btn_Edit.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Edit.OnIdleState.IconLeftImage = null;
            this.btn_Edit.OnIdleState.IconRightImage = null;
            this.btn_Edit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Edit.OnPressedState.BorderRadius = 1;
            this.btn_Edit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.OnPressedState.BorderThickness = 1;
            this.btn_Edit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Edit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Edit.OnPressedState.IconLeftImage = null;
            this.btn_Edit.OnPressedState.IconRightImage = null;
            this.btn_Edit.Size = new System.Drawing.Size(150, 39);
            this.btn_Edit.TabIndex = 13;
            this.btn_Edit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Edit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Edit.TextMarginLeft = 0;
            this.btn_Edit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_Edit.UseDefaultRadiusAndThickness = true;
            this.btn_Edit.Click += new System.EventHandler(this.btn_Edit_Click);
            // 
            // btn_delete
            // 
            this.btn_delete.AllowAnimations = true;
            this.btn_delete.AllowMouseEffects = true;
            this.btn_delete.AllowToggling = false;
            this.btn_delete.AnimationSpeed = 200;
            this.btn_delete.AutoGenerateColors = false;
            this.btn_delete.AutoRoundBorders = false;
            this.btn_delete.AutoSizeLeftIcon = true;
            this.btn_delete.AutoSizeRightIcon = true;
            this.btn_delete.BackColor = System.Drawing.Color.Transparent;
            this.btn_delete.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_delete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_delete.BackgroundImage")));
            this.btn_delete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.ButtonText = "حذف";
            this.btn_delete.ButtonTextMarginLeft = 0;
            this.btn_delete.ColorContrastOnClick = 45;
            this.btn_delete.ColorContrastOnHover = 45;
            this.btn_delete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_delete.CustomizableEdges = borderEdges8;
            this.btn_delete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_delete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_delete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_delete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_delete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_delete.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.btn_delete.ForeColor = System.Drawing.Color.White;
            this.btn_delete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_delete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_delete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_delete.IconMarginLeft = 11;
            this.btn_delete.IconPadding = 10;
            this.btn_delete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_delete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_delete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_delete.IconSize = 25;
            this.btn_delete.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_delete.IdleBorderRadius = 1;
            this.btn_delete.IdleBorderThickness = 1;
            this.btn_delete.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_delete.IdleIconLeftImage = null;
            this.btn_delete.IdleIconRightImage = null;
            this.btn_delete.IndicateFocus = false;
            this.btn_delete.Location = new System.Drawing.Point(17, 34);
            this.btn_delete.Name = "btn_delete";
            this.btn_delete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_delete.OnDisabledState.BorderRadius = 1;
            this.btn_delete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnDisabledState.BorderThickness = 1;
            this.btn_delete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_delete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_delete.OnDisabledState.IconLeftImage = null;
            this.btn_delete.OnDisabledState.IconRightImage = null;
            this.btn_delete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_delete.onHoverState.BorderRadius = 1;
            this.btn_delete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.onHoverState.BorderThickness = 1;
            this.btn_delete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_delete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.onHoverState.IconLeftImage = null;
            this.btn_delete.onHoverState.IconRightImage = null;
            this.btn_delete.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_delete.OnIdleState.BorderRadius = 1;
            this.btn_delete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnIdleState.BorderThickness = 1;
            this.btn_delete.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_delete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.OnIdleState.IconLeftImage = null;
            this.btn_delete.OnIdleState.IconRightImage = null;
            this.btn_delete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_delete.OnPressedState.BorderRadius = 1;
            this.btn_delete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnPressedState.BorderThickness = 1;
            this.btn_delete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_delete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.OnPressedState.IconLeftImage = null;
            this.btn_delete.OnPressedState.IconRightImage = null;
            this.btn_delete.Size = new System.Drawing.Size(150, 39);
            this.btn_delete.TabIndex = 12;
            this.btn_delete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_delete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_delete.TextMarginLeft = 0;
            this.btn_delete.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_delete.UseDefaultRadiusAndThickness = true;
            this.btn_delete.Click += new System.EventHandler(this.btn_delete_Click);
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.BorderRadius = 1;
            this.bunifuShadowPanel2.BorderThickness = 1;
            this.bunifuShadowPanel2.Controls.Add(this.tr_account);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(467, 39);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 5;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(370, 486);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 15;
            // 
            // tr_account
            // 
            this.tr_account.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tr_account.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.tr_account.Location = new System.Drawing.Point(0, 0);
            this.tr_account.Name = "tr_account";
            this.tr_account.RightToLeftLayout = true;
            this.tr_account.Size = new System.Drawing.Size(370, 486);
            this.tr_account.TabIndex = 80;
            this.tr_account.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.tr_account_AfterSelect);
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 1;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.txt_acc_debit);
            this.bunifuShadowPanel1.Controls.Add(this.txt_acc_parent_no);
            this.bunifuShadowPanel1.Controls.Add(this.txt_acc_balance);
            this.bunifuShadowPanel1.Controls.Add(this.txt_acc_credit);
            this.bunifuShadowPanel1.Controls.Add(this.txt_acc_level);
            this.bunifuShadowPanel1.Controls.Add(this.txt_acc_name);
            this.bunifuShadowPanel1.Controls.Add(this.label2);
            this.bunifuShadowPanel1.Controls.Add(this.txt_accNo);
            this.bunifuShadowPanel1.Controls.Add(this.cb_AccType);
            this.bunifuShadowPanel1.Controls.Add(this.label3);
            this.bunifuShadowPanel1.Controls.Add(this.label9);
            this.bunifuShadowPanel1.Controls.Add(this.cb_report);
            this.bunifuShadowPanel1.Controls.Add(this.label5);
            this.bunifuShadowPanel1.Controls.Add(this.label8);
            this.bunifuShadowPanel1.Controls.Add(this.label7);
            this.bunifuShadowPanel1.Controls.Add(this.label6);
            this.bunifuShadowPanel1.Controls.Add(this.label4);
            this.bunifuShadowPanel1.Controls.Add(this.label1);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(12, 30);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(443, 495);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 90;
            // 
            // txt_acc_debit
            // 
            this.txt_acc_debit.AcceptsReturn = false;
            this.txt_acc_debit.AcceptsTab = false;
            this.txt_acc_debit.AnimationSpeed = 200;
            this.txt_acc_debit.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_acc_debit.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_acc_debit.BackColor = System.Drawing.Color.Transparent;
            this.txt_acc_debit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_acc_debit.BackgroundImage")));
            this.txt_acc_debit.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_acc_debit.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_acc_debit.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_acc_debit.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_acc_debit.BorderRadius = 15;
            this.txt_acc_debit.BorderThickness = 1;
            this.txt_acc_debit.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_acc_debit.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_debit.DefaultFont = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.txt_acc_debit.DefaultText = "";
            this.txt_acc_debit.FillColor = System.Drawing.Color.White;
            this.txt_acc_debit.HideSelection = true;
            this.txt_acc_debit.IconLeft = null;
            this.txt_acc_debit.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_debit.IconPadding = 10;
            this.txt_acc_debit.IconRight = null;
            this.txt_acc_debit.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_debit.Lines = new string[0];
            this.txt_acc_debit.Location = new System.Drawing.Point(37, 227);
            this.txt_acc_debit.MaxLength = 32767;
            this.txt_acc_debit.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_acc_debit.Modified = false;
            this.txt_acc_debit.Multiline = false;
            this.txt_acc_debit.Name = "txt_acc_debit";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_debit.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_acc_debit.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_debit.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_debit.OnIdleState = stateProperties32;
            this.txt_acc_debit.Padding = new System.Windows.Forms.Padding(3);
            this.txt_acc_debit.PasswordChar = '\0';
            this.txt_acc_debit.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_acc_debit.PlaceholderText = "";
            this.txt_acc_debit.ReadOnly = false;
            this.txt_acc_debit.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_acc_debit.SelectedText = "";
            this.txt_acc_debit.SelectionLength = 0;
            this.txt_acc_debit.SelectionStart = 0;
            this.txt_acc_debit.ShortcutsEnabled = true;
            this.txt_acc_debit.Size = new System.Drawing.Size(260, 45);
            this.txt_acc_debit.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_acc_debit.TabIndex = 5;
            this.txt_acc_debit.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_acc_debit.TextMarginBottom = 0;
            this.txt_acc_debit.TextMarginLeft = 3;
            this.txt_acc_debit.TextMarginTop = 0;
            this.txt_acc_debit.TextPlaceholder = "";
            this.txt_acc_debit.UseSystemPasswordChar = false;
            this.txt_acc_debit.WordWrap = true;
            this.txt_acc_debit.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_acc_debit_KeyPress);
            // 
            // txt_acc_parent_no
            // 
            this.txt_acc_parent_no.AcceptsReturn = false;
            this.txt_acc_parent_no.AcceptsTab = false;
            this.txt_acc_parent_no.AnimationSpeed = 200;
            this.txt_acc_parent_no.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_acc_parent_no.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_acc_parent_no.BackColor = System.Drawing.Color.Transparent;
            this.txt_acc_parent_no.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_acc_parent_no.BackgroundImage")));
            this.txt_acc_parent_no.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_acc_parent_no.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_acc_parent_no.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_acc_parent_no.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_acc_parent_no.BorderRadius = 15;
            this.txt_acc_parent_no.BorderThickness = 1;
            this.txt_acc_parent_no.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_acc_parent_no.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_parent_no.DefaultFont = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.txt_acc_parent_no.DefaultText = "";
            this.txt_acc_parent_no.FillColor = System.Drawing.Color.White;
            this.txt_acc_parent_no.HideSelection = true;
            this.txt_acc_parent_no.IconLeft = null;
            this.txt_acc_parent_no.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_parent_no.IconPadding = 10;
            this.txt_acc_parent_no.IconRight = null;
            this.txt_acc_parent_no.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_parent_no.Lines = new string[0];
            this.txt_acc_parent_no.Location = new System.Drawing.Point(37, 76);
            this.txt_acc_parent_no.MaxLength = 32767;
            this.txt_acc_parent_no.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_acc_parent_no.Modified = false;
            this.txt_acc_parent_no.Multiline = false;
            this.txt_acc_parent_no.Name = "txt_acc_parent_no";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_parent_no.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_acc_parent_no.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_parent_no.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_parent_no.OnIdleState = stateProperties36;
            this.txt_acc_parent_no.Padding = new System.Windows.Forms.Padding(3);
            this.txt_acc_parent_no.PasswordChar = '\0';
            this.txt_acc_parent_no.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_acc_parent_no.PlaceholderText = "";
            this.txt_acc_parent_no.ReadOnly = false;
            this.txt_acc_parent_no.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_acc_parent_no.SelectedText = "";
            this.txt_acc_parent_no.SelectionLength = 0;
            this.txt_acc_parent_no.SelectionStart = 0;
            this.txt_acc_parent_no.ShortcutsEnabled = true;
            this.txt_acc_parent_no.Size = new System.Drawing.Size(260, 45);
            this.txt_acc_parent_no.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_acc_parent_no.TabIndex = 2;
            this.txt_acc_parent_no.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_acc_parent_no.TextMarginBottom = 0;
            this.txt_acc_parent_no.TextMarginLeft = 3;
            this.txt_acc_parent_no.TextMarginTop = 0;
            this.txt_acc_parent_no.TextPlaceholder = "";
            this.txt_acc_parent_no.UseSystemPasswordChar = false;
            this.txt_acc_parent_no.WordWrap = true;
            this.txt_acc_parent_no.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_acc_parent_no_KeyPress);
            // 
            // txt_acc_balance
            // 
            this.txt_acc_balance.AcceptsReturn = false;
            this.txt_acc_balance.AcceptsTab = false;
            this.txt_acc_balance.AnimationSpeed = 200;
            this.txt_acc_balance.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_acc_balance.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_acc_balance.BackColor = System.Drawing.Color.Transparent;
            this.txt_acc_balance.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_acc_balance.BackgroundImage")));
            this.txt_acc_balance.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_acc_balance.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_acc_balance.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_acc_balance.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_acc_balance.BorderRadius = 15;
            this.txt_acc_balance.BorderThickness = 1;
            this.txt_acc_balance.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_acc_balance.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_balance.DefaultFont = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.txt_acc_balance.DefaultText = "";
            this.txt_acc_balance.FillColor = System.Drawing.Color.White;
            this.txt_acc_balance.HideSelection = true;
            this.txt_acc_balance.IconLeft = null;
            this.txt_acc_balance.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_balance.IconPadding = 10;
            this.txt_acc_balance.IconRight = null;
            this.txt_acc_balance.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_balance.Lines = new string[0];
            this.txt_acc_balance.Location = new System.Drawing.Point(37, 332);
            this.txt_acc_balance.MaxLength = 32767;
            this.txt_acc_balance.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_acc_balance.Modified = false;
            this.txt_acc_balance.Multiline = false;
            this.txt_acc_balance.Name = "txt_acc_balance";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_balance.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_acc_balance.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_balance.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_balance.OnIdleState = stateProperties40;
            this.txt_acc_balance.Padding = new System.Windows.Forms.Padding(3);
            this.txt_acc_balance.PasswordChar = '\0';
            this.txt_acc_balance.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_acc_balance.PlaceholderText = "";
            this.txt_acc_balance.ReadOnly = false;
            this.txt_acc_balance.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_acc_balance.SelectedText = "";
            this.txt_acc_balance.SelectionLength = 0;
            this.txt_acc_balance.SelectionStart = 0;
            this.txt_acc_balance.ShortcutsEnabled = true;
            this.txt_acc_balance.Size = new System.Drawing.Size(260, 45);
            this.txt_acc_balance.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_acc_balance.TabIndex = 7;
            this.txt_acc_balance.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_acc_balance.TextMarginBottom = 0;
            this.txt_acc_balance.TextMarginLeft = 3;
            this.txt_acc_balance.TextMarginTop = 0;
            this.txt_acc_balance.TextPlaceholder = "";
            this.txt_acc_balance.UseSystemPasswordChar = false;
            this.txt_acc_balance.WordWrap = true;
            this.txt_acc_balance.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_acc_balance_KeyPress);
            // 
            // txt_acc_credit
            // 
            this.txt_acc_credit.AcceptsReturn = false;
            this.txt_acc_credit.AcceptsTab = false;
            this.txt_acc_credit.AnimationSpeed = 200;
            this.txt_acc_credit.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_acc_credit.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_acc_credit.BackColor = System.Drawing.Color.Transparent;
            this.txt_acc_credit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_acc_credit.BackgroundImage")));
            this.txt_acc_credit.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_acc_credit.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_acc_credit.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_acc_credit.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_acc_credit.BorderRadius = 15;
            this.txt_acc_credit.BorderThickness = 1;
            this.txt_acc_credit.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_acc_credit.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_credit.DefaultFont = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.txt_acc_credit.DefaultText = "";
            this.txt_acc_credit.FillColor = System.Drawing.Color.White;
            this.txt_acc_credit.HideSelection = true;
            this.txt_acc_credit.IconLeft = null;
            this.txt_acc_credit.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_credit.IconPadding = 10;
            this.txt_acc_credit.IconRight = null;
            this.txt_acc_credit.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_credit.Lines = new string[0];
            this.txt_acc_credit.Location = new System.Drawing.Point(37, 280);
            this.txt_acc_credit.MaxLength = 32767;
            this.txt_acc_credit.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_acc_credit.Modified = false;
            this.txt_acc_credit.Multiline = false;
            this.txt_acc_credit.Name = "txt_acc_credit";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_credit.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_acc_credit.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_credit.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_credit.OnIdleState = stateProperties44;
            this.txt_acc_credit.Padding = new System.Windows.Forms.Padding(3);
            this.txt_acc_credit.PasswordChar = '\0';
            this.txt_acc_credit.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_acc_credit.PlaceholderText = "";
            this.txt_acc_credit.ReadOnly = false;
            this.txt_acc_credit.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_acc_credit.SelectedText = "";
            this.txt_acc_credit.SelectionLength = 0;
            this.txt_acc_credit.SelectionStart = 0;
            this.txt_acc_credit.ShortcutsEnabled = true;
            this.txt_acc_credit.Size = new System.Drawing.Size(260, 45);
            this.txt_acc_credit.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_acc_credit.TabIndex = 6;
            this.txt_acc_credit.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_acc_credit.TextMarginBottom = 0;
            this.txt_acc_credit.TextMarginLeft = 3;
            this.txt_acc_credit.TextMarginTop = 0;
            this.txt_acc_credit.TextPlaceholder = "";
            this.txt_acc_credit.UseSystemPasswordChar = false;
            this.txt_acc_credit.WordWrap = true;
            this.txt_acc_credit.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_acc_credit_KeyPress);
            // 
            // txt_acc_level
            // 
            this.txt_acc_level.AcceptsReturn = false;
            this.txt_acc_level.AcceptsTab = false;
            this.txt_acc_level.AnimationSpeed = 200;
            this.txt_acc_level.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_acc_level.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_acc_level.BackColor = System.Drawing.Color.Transparent;
            this.txt_acc_level.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_acc_level.BackgroundImage")));
            this.txt_acc_level.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_acc_level.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_acc_level.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_acc_level.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_acc_level.BorderRadius = 15;
            this.txt_acc_level.BorderThickness = 1;
            this.txt_acc_level.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_acc_level.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_level.DefaultFont = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.txt_acc_level.DefaultText = "";
            this.txt_acc_level.FillColor = System.Drawing.Color.White;
            this.txt_acc_level.HideSelection = true;
            this.txt_acc_level.IconLeft = null;
            this.txt_acc_level.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_level.IconPadding = 10;
            this.txt_acc_level.IconRight = null;
            this.txt_acc_level.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_level.Lines = new string[0];
            this.txt_acc_level.Location = new System.Drawing.Point(37, 176);
            this.txt_acc_level.MaxLength = 32767;
            this.txt_acc_level.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_acc_level.Modified = false;
            this.txt_acc_level.Multiline = false;
            this.txt_acc_level.Name = "txt_acc_level";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_level.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_acc_level.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_level.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_level.OnIdleState = stateProperties48;
            this.txt_acc_level.Padding = new System.Windows.Forms.Padding(3);
            this.txt_acc_level.PasswordChar = '\0';
            this.txt_acc_level.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_acc_level.PlaceholderText = "";
            this.txt_acc_level.ReadOnly = false;
            this.txt_acc_level.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_acc_level.SelectedText = "";
            this.txt_acc_level.SelectionLength = 0;
            this.txt_acc_level.SelectionStart = 0;
            this.txt_acc_level.ShortcutsEnabled = true;
            this.txt_acc_level.Size = new System.Drawing.Size(260, 45);
            this.txt_acc_level.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_acc_level.TabIndex = 4;
            this.txt_acc_level.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_acc_level.TextMarginBottom = 0;
            this.txt_acc_level.TextMarginLeft = 3;
            this.txt_acc_level.TextMarginTop = 0;
            this.txt_acc_level.TextPlaceholder = "";
            this.txt_acc_level.UseSystemPasswordChar = false;
            this.txt_acc_level.WordWrap = true;
            this.txt_acc_level.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_acc_level_KeyPress);
            // 
            // txt_acc_name
            // 
            this.txt_acc_name.AcceptsReturn = false;
            this.txt_acc_name.AcceptsTab = false;
            this.txt_acc_name.AnimationSpeed = 200;
            this.txt_acc_name.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_acc_name.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_acc_name.BackColor = System.Drawing.Color.Transparent;
            this.txt_acc_name.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_acc_name.BackgroundImage")));
            this.txt_acc_name.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_acc_name.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_acc_name.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_acc_name.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_acc_name.BorderRadius = 15;
            this.txt_acc_name.BorderThickness = 1;
            this.txt_acc_name.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_acc_name.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_name.DefaultFont = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.txt_acc_name.DefaultText = "";
            this.txt_acc_name.FillColor = System.Drawing.Color.White;
            this.txt_acc_name.HideSelection = true;
            this.txt_acc_name.IconLeft = null;
            this.txt_acc_name.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_name.IconPadding = 10;
            this.txt_acc_name.IconRight = null;
            this.txt_acc_name.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_acc_name.Lines = new string[0];
            this.txt_acc_name.Location = new System.Drawing.Point(37, 125);
            this.txt_acc_name.MaxLength = 32767;
            this.txt_acc_name.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_acc_name.Modified = false;
            this.txt_acc_name.Multiline = false;
            this.txt_acc_name.Name = "txt_acc_name";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_name.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_acc_name.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_name.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_acc_name.OnIdleState = stateProperties52;
            this.txt_acc_name.Padding = new System.Windows.Forms.Padding(3);
            this.txt_acc_name.PasswordChar = '\0';
            this.txt_acc_name.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_acc_name.PlaceholderText = "";
            this.txt_acc_name.ReadOnly = false;
            this.txt_acc_name.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_acc_name.SelectedText = "";
            this.txt_acc_name.SelectionLength = 0;
            this.txt_acc_name.SelectionStart = 0;
            this.txt_acc_name.ShortcutsEnabled = true;
            this.txt_acc_name.Size = new System.Drawing.Size(260, 45);
            this.txt_acc_name.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_acc_name.TabIndex = 3;
            this.txt_acc_name.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_acc_name.TextMarginBottom = 0;
            this.txt_acc_name.TextMarginLeft = 3;
            this.txt_acc_name.TextMarginTop = 0;
            this.txt_acc_name.TextPlaceholder = "";
            this.txt_acc_name.UseSystemPasswordChar = false;
            this.txt_acc_name.WordWrap = true;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(327, 436);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(73, 24);
            this.label2.TabIndex = 6;
            this.label2.Text = "نوع الحساب";
            // 
            // txt_accNo
            // 
            this.txt_accNo.AcceptsReturn = false;
            this.txt_accNo.AcceptsTab = false;
            this.txt_accNo.AnimationSpeed = 200;
            this.txt_accNo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_accNo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_accNo.BackColor = System.Drawing.Color.Transparent;
            this.txt_accNo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_accNo.BackgroundImage")));
            this.txt_accNo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_accNo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_accNo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_accNo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_accNo.BorderRadius = 15;
            this.txt_accNo.BorderThickness = 1;
            this.txt_accNo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_accNo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_accNo.DefaultFont = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.txt_accNo.DefaultText = "";
            this.txt_accNo.Enabled = false;
            this.txt_accNo.FillColor = System.Drawing.Color.White;
            this.txt_accNo.HideSelection = true;
            this.txt_accNo.IconLeft = null;
            this.txt_accNo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_accNo.IconPadding = 10;
            this.txt_accNo.IconRight = null;
            this.txt_accNo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_accNo.Lines = new string[0];
            this.txt_accNo.Location = new System.Drawing.Point(37, 25);
            this.txt_accNo.MaxLength = 32767;
            this.txt_accNo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_accNo.Modified = false;
            this.txt_accNo.Multiline = false;
            this.txt_accNo.Name = "txt_accNo";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_accNo.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_accNo.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_accNo.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_accNo.OnIdleState = stateProperties56;
            this.txt_accNo.Padding = new System.Windows.Forms.Padding(3);
            this.txt_accNo.PasswordChar = '\0';
            this.txt_accNo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_accNo.PlaceholderText = "";
            this.txt_accNo.ReadOnly = false;
            this.txt_accNo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_accNo.SelectedText = "";
            this.txt_accNo.SelectionLength = 0;
            this.txt_accNo.SelectionStart = 0;
            this.txt_accNo.ShortcutsEnabled = true;
            this.txt_accNo.Size = new System.Drawing.Size(260, 45);
            this.txt_accNo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_accNo.TabIndex = 1;
            this.txt_accNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_accNo.TextMarginBottom = 0;
            this.txt_accNo.TextMarginLeft = 3;
            this.txt_accNo.TextMarginTop = 0;
            this.txt_accNo.TextPlaceholder = "";
            this.txt_accNo.UseSystemPasswordChar = false;
            this.txt_accNo.WordWrap = true;
            this.txt_accNo.TextChange += new System.EventHandler(this.txt_accNo_TextChanged);
            this.txt_accNo.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_accNo_KeyPress);
            // 
            // cb_AccType
            // 
            this.cb_AccType.BackColor = System.Drawing.Color.Transparent;
            this.cb_AccType.BackgroundColor = System.Drawing.Color.White;
            this.cb_AccType.BorderColor = System.Drawing.Color.Silver;
            this.cb_AccType.BorderRadius = 15;
            this.cb_AccType.Color = System.Drawing.Color.Silver;
            this.cb_AccType.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cb_AccType.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cb_AccType.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cb_AccType.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cb_AccType.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cb_AccType.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cb_AccType.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cb_AccType.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cb_AccType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cb_AccType.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Right;
            this.cb_AccType.FillDropDown = true;
            this.cb_AccType.FillIndicator = false;
            this.cb_AccType.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cb_AccType.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.cb_AccType.ForeColor = System.Drawing.Color.Black;
            this.cb_AccType.FormattingEnabled = true;
            this.cb_AccType.Icon = null;
            this.cb_AccType.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Left;
            this.cb_AccType.IndicatorColor = System.Drawing.Color.Gray;
            this.cb_AccType.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Left;
            this.cb_AccType.ItemBackColor = System.Drawing.Color.White;
            this.cb_AccType.ItemBorderColor = System.Drawing.Color.White;
            this.cb_AccType.ItemForeColor = System.Drawing.Color.Black;
            this.cb_AccType.ItemHeight = 26;
            this.cb_AccType.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cb_AccType.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cb_AccType.ItemTopMargin = 3;
            this.cb_AccType.Location = new System.Drawing.Point(37, 433);
            this.cb_AccType.Name = "cb_AccType";
            this.cb_AccType.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.cb_AccType.Size = new System.Drawing.Size(260, 32);
            this.cb_AccType.TabIndex = 9;
            this.cb_AccType.Text = null;
            this.cb_AccType.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Right;
            this.cb_AccType.TextLeftMargin = 5;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(357, 391);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(43, 24);
            this.label3.TabIndex = 7;
            this.label3.Text = "التقرير";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(362, 237);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(38, 24);
            this.label9.TabIndex = 10;
            this.label9.Text = "مدين";
            // 
            // cb_report
            // 
            this.cb_report.BackColor = System.Drawing.Color.Transparent;
            this.cb_report.BackgroundColor = System.Drawing.Color.White;
            this.cb_report.BorderColor = System.Drawing.Color.Silver;
            this.cb_report.BorderRadius = 15;
            this.cb_report.Color = System.Drawing.Color.Silver;
            this.cb_report.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cb_report.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cb_report.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cb_report.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cb_report.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cb_report.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cb_report.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cb_report.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cb_report.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cb_report.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Right;
            this.cb_report.FillDropDown = true;
            this.cb_report.FillIndicator = false;
            this.cb_report.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cb_report.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold);
            this.cb_report.ForeColor = System.Drawing.Color.Black;
            this.cb_report.FormattingEnabled = true;
            this.cb_report.Icon = null;
            this.cb_report.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Left;
            this.cb_report.IndicatorColor = System.Drawing.Color.Gray;
            this.cb_report.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Left;
            this.cb_report.ItemBackColor = System.Drawing.Color.White;
            this.cb_report.ItemBorderColor = System.Drawing.Color.White;
            this.cb_report.ItemForeColor = System.Drawing.Color.Black;
            this.cb_report.ItemHeight = 26;
            this.cb_report.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cb_report.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cb_report.ItemTopMargin = 3;
            this.cb_report.Location = new System.Drawing.Point(37, 388);
            this.cb_report.Name = "cb_report";
            this.cb_report.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.cb_report.Size = new System.Drawing.Size(260, 32);
            this.cb_report.TabIndex = 8;
            this.cb_report.Text = null;
            this.cb_report.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Right;
            this.cb_report.TextLeftMargin = 5;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(323, 86);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(77, 24);
            this.label5.TabIndex = 11;
            this.label5.Text = "الحساب الأب";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(364, 342);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(36, 24);
            this.label8.TabIndex = 12;
            this.label8.Text = "رصيد";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(367, 290);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(33, 24);
            this.label7.TabIndex = 13;
            this.label7.Text = "دائن";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(303, 186);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(97, 24);
            this.label6.TabIndex = 14;
            this.label6.Text = "مستوى الحساب";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(322, 135);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(78, 24);
            this.label4.TabIndex = 15;
            this.label4.Text = "اسم الحساب";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Cairo SemiBold", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(325, 35);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(75, 24);
            this.label1.TabIndex = 16;
            this.label1.Text = "رقم الحساب";
            // 
            // frm_accounts
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(858, 684);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frm_accounts";
            this.Text = "frm_accounts";
            this.panel1.ResumeLayout(false);
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuDropdown cb_AccType;
        private Bunifu.UI.WinForms.BunifuDropdown cb_report;
        private System.Windows.Forms.TreeView tr_account;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox txt_acc_debit;
        private Bunifu.UI.WinForms.BunifuTextBox txt_acc_parent_no;
        private Bunifu.UI.WinForms.BunifuTextBox txt_acc_balance;
        private Bunifu.UI.WinForms.BunifuTextBox txt_acc_credit;
        private Bunifu.UI.WinForms.BunifuTextBox txt_acc_level;
        private Bunifu.UI.WinForms.BunifuTextBox txt_acc_name;
        private Bunifu.UI.WinForms.BunifuTextBox txt_accNo;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_new;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_delete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Edit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Save;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel3;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
    }
}