namespace demo.PL.Currency
{
    partial class frm_Currency
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frm_Currency));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuShadowPanel4 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.rb_foreigner_currency = new System.Windows.Forms.RadioButton();
            this.rb_local_currency = new System.Windows.Forms.RadioButton();
            this.txt_currency_symbol = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_currency_decent = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_currency_ename = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_currency_exchange = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txt_currency_aname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btn_new = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_Save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_Edit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_delete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.dgv_currency = new Bunifu.Framework.UI.BunifuCustomDataGrid();
            this.CurrencyIDColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.CurrencyNameColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.bunifuShadowPanel4.SuspendLayout();
            this.bunifuShadowPanel3.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv_currency)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel4
            // 
            this.bunifuShadowPanel4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel4.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel4.BorderRadius = 1;
            this.bunifuShadowPanel4.BorderThickness = 1;
            this.bunifuShadowPanel4.Controls.Add(this.rb_foreigner_currency);
            this.bunifuShadowPanel4.Controls.Add(this.rb_local_currency);
            this.bunifuShadowPanel4.Controls.Add(this.txt_currency_symbol);
            this.bunifuShadowPanel4.Controls.Add(this.txt_currency_decent);
            this.bunifuShadowPanel4.Controls.Add(this.txt_currency_ename);
            this.bunifuShadowPanel4.Controls.Add(this.txt_currency_exchange);
            this.bunifuShadowPanel4.Controls.Add(this.label4);
            this.bunifuShadowPanel4.Controls.Add(this.txt_currency_aname);
            this.bunifuShadowPanel4.Controls.Add(this.label3);
            this.bunifuShadowPanel4.Controls.Add(this.label1);
            this.bunifuShadowPanel4.Controls.Add(this.label2);
            this.bunifuShadowPanel4.Controls.Add(this.label6);
            this.bunifuShadowPanel4.Controls.Add(this.label5);
            this.bunifuShadowPanel4.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel4.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel4.Location = new System.Drawing.Point(29, 228);
            this.bunifuShadowPanel4.Name = "bunifuShadowPanel4";
            this.bunifuShadowPanel4.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel4.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel4.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel4.ShadowDept = 2;
            this.bunifuShadowPanel4.ShadowDepth = 5;
            this.bunifuShadowPanel4.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel4.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel4.Size = new System.Drawing.Size(817, 352);
            this.bunifuShadowPanel4.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel4.TabIndex = 18;
            // 
            // rb_foreigner_currency
            // 
            this.rb_foreigner_currency.AutoSize = true;
            this.rb_foreigner_currency.Checked = true;
            this.rb_foreigner_currency.Enabled = false;
            this.rb_foreigner_currency.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.rb_foreigner_currency.Location = new System.Drawing.Point(203, 284);
            this.rb_foreigner_currency.Name = "rb_foreigner_currency";
            this.rb_foreigner_currency.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.rb_foreigner_currency.Size = new System.Drawing.Size(109, 33);
            this.rb_foreigner_currency.TabIndex = 7;
            this.rb_foreigner_currency.TabStop = true;
            this.rb_foreigner_currency.Text = "عملة اجنبية";
            this.rb_foreigner_currency.UseVisualStyleBackColor = true;
            // 
            // rb_local_currency
            // 
            this.rb_local_currency.AutoSize = true;
            this.rb_local_currency.Enabled = false;
            this.rb_local_currency.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.rb_local_currency.Location = new System.Drawing.Point(400, 282);
            this.rb_local_currency.Name = "rb_local_currency";
            this.rb_local_currency.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.rb_local_currency.Size = new System.Drawing.Size(106, 33);
            this.rb_local_currency.TabIndex = 6;
            this.rb_local_currency.Text = "عملة محلي";
            this.rb_local_currency.UseVisualStyleBackColor = true;
            // 
            // txt_currency_symbol
            // 
            this.txt_currency_symbol.AcceptsReturn = false;
            this.txt_currency_symbol.AcceptsTab = false;
            this.txt_currency_symbol.AnimationSpeed = 200;
            this.txt_currency_symbol.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_currency_symbol.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_currency_symbol.BackColor = System.Drawing.Color.Transparent;
            this.txt_currency_symbol.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_currency_symbol.BackgroundImage")));
            this.txt_currency_symbol.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_currency_symbol.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_currency_symbol.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_currency_symbol.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_currency_symbol.BorderRadius = 15;
            this.txt_currency_symbol.BorderThickness = 1;
            this.txt_currency_symbol.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_currency_symbol.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_symbol.DefaultFont = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_currency_symbol.DefaultText = "";
            this.txt_currency_symbol.Enabled = false;
            this.txt_currency_symbol.FillColor = System.Drawing.Color.White;
            this.txt_currency_symbol.HideSelection = true;
            this.txt_currency_symbol.IconLeft = null;
            this.txt_currency_symbol.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_symbol.IconPadding = 10;
            this.txt_currency_symbol.IconRight = null;
            this.txt_currency_symbol.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_symbol.Lines = new string[0];
            this.txt_currency_symbol.Location = new System.Drawing.Point(139, 133);
            this.txt_currency_symbol.MaxLength = 32767;
            this.txt_currency_symbol.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_currency_symbol.Modified = false;
            this.txt_currency_symbol.Multiline = false;
            this.txt_currency_symbol.Name = "txt_currency_symbol";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_symbol.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_currency_symbol.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_symbol.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_symbol.OnIdleState = stateProperties4;
            this.txt_currency_symbol.Padding = new System.Windows.Forms.Padding(3);
            this.txt_currency_symbol.PasswordChar = '\0';
            this.txt_currency_symbol.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_currency_symbol.PlaceholderText = "";
            this.txt_currency_symbol.ReadOnly = false;
            this.txt_currency_symbol.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_currency_symbol.SelectedText = "";
            this.txt_currency_symbol.SelectionLength = 0;
            this.txt_currency_symbol.SelectionStart = 0;
            this.txt_currency_symbol.ShortcutsEnabled = true;
            this.txt_currency_symbol.Size = new System.Drawing.Size(391, 43);
            this.txt_currency_symbol.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_currency_symbol.TabIndex = 3;
            this.txt_currency_symbol.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txt_currency_symbol.TextMarginBottom = 0;
            this.txt_currency_symbol.TextMarginLeft = 3;
            this.txt_currency_symbol.TextMarginTop = 0;
            this.txt_currency_symbol.TextPlaceholder = "";
            this.txt_currency_symbol.UseSystemPasswordChar = false;
            this.txt_currency_symbol.WordWrap = true;
            // 
            // txt_currency_decent
            // 
            this.txt_currency_decent.AcceptsReturn = false;
            this.txt_currency_decent.AcceptsTab = false;
            this.txt_currency_decent.AnimationSpeed = 200;
            this.txt_currency_decent.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_currency_decent.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_currency_decent.BackColor = System.Drawing.Color.Transparent;
            this.txt_currency_decent.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_currency_decent.BackgroundImage")));
            this.txt_currency_decent.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_currency_decent.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_currency_decent.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_currency_decent.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_currency_decent.BorderRadius = 15;
            this.txt_currency_decent.BorderThickness = 1;
            this.txt_currency_decent.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_currency_decent.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_decent.DefaultFont = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_currency_decent.DefaultText = "";
            this.txt_currency_decent.Enabled = false;
            this.txt_currency_decent.FillColor = System.Drawing.Color.White;
            this.txt_currency_decent.HideSelection = true;
            this.txt_currency_decent.IconLeft = null;
            this.txt_currency_decent.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_decent.IconPadding = 10;
            this.txt_currency_decent.IconRight = null;
            this.txt_currency_decent.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_decent.Lines = new string[0];
            this.txt_currency_decent.Location = new System.Drawing.Point(139, 231);
            this.txt_currency_decent.MaxLength = 32767;
            this.txt_currency_decent.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_currency_decent.Modified = false;
            this.txt_currency_decent.Multiline = false;
            this.txt_currency_decent.Name = "txt_currency_decent";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_decent.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_currency_decent.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_decent.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_decent.OnIdleState = stateProperties8;
            this.txt_currency_decent.Padding = new System.Windows.Forms.Padding(3);
            this.txt_currency_decent.PasswordChar = '\0';
            this.txt_currency_decent.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_currency_decent.PlaceholderText = "";
            this.txt_currency_decent.ReadOnly = false;
            this.txt_currency_decent.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_currency_decent.SelectedText = "";
            this.txt_currency_decent.SelectionLength = 0;
            this.txt_currency_decent.SelectionStart = 0;
            this.txt_currency_decent.ShortcutsEnabled = true;
            this.txt_currency_decent.Size = new System.Drawing.Size(391, 43);
            this.txt_currency_decent.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_currency_decent.TabIndex = 5;
            this.txt_currency_decent.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txt_currency_decent.TextMarginBottom = 0;
            this.txt_currency_decent.TextMarginLeft = 3;
            this.txt_currency_decent.TextMarginTop = 0;
            this.txt_currency_decent.TextPlaceholder = "";
            this.txt_currency_decent.UseSystemPasswordChar = false;
            this.txt_currency_decent.WordWrap = true;
            // 
            // txt_currency_ename
            // 
            this.txt_currency_ename.AcceptsReturn = false;
            this.txt_currency_ename.AcceptsTab = false;
            this.txt_currency_ename.AnimationSpeed = 200;
            this.txt_currency_ename.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_currency_ename.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_currency_ename.BackColor = System.Drawing.Color.Transparent;
            this.txt_currency_ename.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_currency_ename.BackgroundImage")));
            this.txt_currency_ename.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_currency_ename.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_currency_ename.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_currency_ename.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_currency_ename.BorderRadius = 15;
            this.txt_currency_ename.BorderThickness = 1;
            this.txt_currency_ename.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_currency_ename.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_ename.DefaultFont = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_currency_ename.DefaultText = "";
            this.txt_currency_ename.Enabled = false;
            this.txt_currency_ename.FillColor = System.Drawing.Color.White;
            this.txt_currency_ename.HideSelection = true;
            this.txt_currency_ename.IconLeft = null;
            this.txt_currency_ename.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_ename.IconPadding = 10;
            this.txt_currency_ename.IconRight = null;
            this.txt_currency_ename.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_ename.Lines = new string[0];
            this.txt_currency_ename.Location = new System.Drawing.Point(139, 84);
            this.txt_currency_ename.MaxLength = 32767;
            this.txt_currency_ename.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_currency_ename.Modified = false;
            this.txt_currency_ename.Multiline = false;
            this.txt_currency_ename.Name = "txt_currency_ename";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_ename.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_currency_ename.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_ename.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_ename.OnIdleState = stateProperties12;
            this.txt_currency_ename.Padding = new System.Windows.Forms.Padding(3);
            this.txt_currency_ename.PasswordChar = '\0';
            this.txt_currency_ename.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_currency_ename.PlaceholderText = "";
            this.txt_currency_ename.ReadOnly = false;
            this.txt_currency_ename.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_currency_ename.SelectedText = "";
            this.txt_currency_ename.SelectionLength = 0;
            this.txt_currency_ename.SelectionStart = 0;
            this.txt_currency_ename.ShortcutsEnabled = true;
            this.txt_currency_ename.Size = new System.Drawing.Size(391, 43);
            this.txt_currency_ename.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_currency_ename.TabIndex = 2;
            this.txt_currency_ename.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txt_currency_ename.TextMarginBottom = 0;
            this.txt_currency_ename.TextMarginLeft = 3;
            this.txt_currency_ename.TextMarginTop = 0;
            this.txt_currency_ename.TextPlaceholder = "";
            this.txt_currency_ename.UseSystemPasswordChar = false;
            this.txt_currency_ename.WordWrap = true;
            // 
            // txt_currency_exchange
            // 
            this.txt_currency_exchange.AcceptsReturn = false;
            this.txt_currency_exchange.AcceptsTab = false;
            this.txt_currency_exchange.AnimationSpeed = 200;
            this.txt_currency_exchange.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_currency_exchange.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_currency_exchange.BackColor = System.Drawing.Color.Transparent;
            this.txt_currency_exchange.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_currency_exchange.BackgroundImage")));
            this.txt_currency_exchange.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_currency_exchange.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_currency_exchange.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_currency_exchange.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_currency_exchange.BorderRadius = 15;
            this.txt_currency_exchange.BorderThickness = 1;
            this.txt_currency_exchange.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_currency_exchange.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_exchange.DefaultFont = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_currency_exchange.DefaultText = "";
            this.txt_currency_exchange.FillColor = System.Drawing.Color.White;
            this.txt_currency_exchange.HideSelection = true;
            this.txt_currency_exchange.IconLeft = null;
            this.txt_currency_exchange.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_exchange.IconPadding = 10;
            this.txt_currency_exchange.IconRight = null;
            this.txt_currency_exchange.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_exchange.Lines = new string[0];
            this.txt_currency_exchange.Location = new System.Drawing.Point(139, 182);
            this.txt_currency_exchange.MaxLength = 32767;
            this.txt_currency_exchange.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_currency_exchange.Modified = false;
            this.txt_currency_exchange.Multiline = false;
            this.txt_currency_exchange.Name = "txt_currency_exchange";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_exchange.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_currency_exchange.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_exchange.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_exchange.OnIdleState = stateProperties16;
            this.txt_currency_exchange.Padding = new System.Windows.Forms.Padding(3);
            this.txt_currency_exchange.PasswordChar = '\0';
            this.txt_currency_exchange.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_currency_exchange.PlaceholderText = "";
            this.txt_currency_exchange.ReadOnly = false;
            this.txt_currency_exchange.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_currency_exchange.SelectedText = "";
            this.txt_currency_exchange.SelectionLength = 0;
            this.txt_currency_exchange.SelectionStart = 0;
            this.txt_currency_exchange.ShortcutsEnabled = true;
            this.txt_currency_exchange.Size = new System.Drawing.Size(391, 43);
            this.txt_currency_exchange.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_currency_exchange.TabIndex = 4;
            this.txt_currency_exchange.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txt_currency_exchange.TextMarginBottom = 0;
            this.txt_currency_exchange.TextMarginLeft = 3;
            this.txt_currency_exchange.TextMarginTop = 0;
            this.txt_currency_exchange.TextPlaceholder = "";
            this.txt_currency_exchange.UseSystemPasswordChar = false;
            this.txt_currency_exchange.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.label4.Location = new System.Drawing.Point(565, 284);
            this.label4.Name = "label4";
            this.label4.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.label4.Size = new System.Drawing.Size(83, 29);
            this.label4.TabIndex = 2;
            this.label4.Text = "نوع العملة";
            // 
            // txt_currency_aname
            // 
            this.txt_currency_aname.AcceptsReturn = false;
            this.txt_currency_aname.AcceptsTab = false;
            this.txt_currency_aname.AnimationSpeed = 200;
            this.txt_currency_aname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_currency_aname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_currency_aname.BackColor = System.Drawing.Color.Transparent;
            this.txt_currency_aname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_currency_aname.BackgroundImage")));
            this.txt_currency_aname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_currency_aname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_currency_aname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_currency_aname.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_currency_aname.BorderRadius = 15;
            this.txt_currency_aname.BorderThickness = 1;
            this.txt_currency_aname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_currency_aname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_aname.DefaultFont = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_currency_aname.DefaultText = "";
            this.txt_currency_aname.Enabled = false;
            this.txt_currency_aname.FillColor = System.Drawing.Color.White;
            this.txt_currency_aname.HideSelection = true;
            this.txt_currency_aname.IconLeft = null;
            this.txt_currency_aname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_aname.IconPadding = 10;
            this.txt_currency_aname.IconRight = null;
            this.txt_currency_aname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_currency_aname.Lines = new string[0];
            this.txt_currency_aname.Location = new System.Drawing.Point(139, 35);
            this.txt_currency_aname.MaxLength = 32767;
            this.txt_currency_aname.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_currency_aname.Modified = false;
            this.txt_currency_aname.Multiline = false;
            this.txt_currency_aname.Name = "txt_currency_aname";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_aname.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_currency_aname.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_aname.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_currency_aname.OnIdleState = stateProperties20;
            this.txt_currency_aname.Padding = new System.Windows.Forms.Padding(3);
            this.txt_currency_aname.PasswordChar = '\0';
            this.txt_currency_aname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_currency_aname.PlaceholderText = "";
            this.txt_currency_aname.ReadOnly = false;
            this.txt_currency_aname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_currency_aname.SelectedText = "";
            this.txt_currency_aname.SelectionLength = 0;
            this.txt_currency_aname.SelectionStart = 0;
            this.txt_currency_aname.ShortcutsEnabled = true;
            this.txt_currency_aname.Size = new System.Drawing.Size(391, 43);
            this.txt_currency_aname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_currency_aname.TabIndex = 1;
            this.txt_currency_aname.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txt_currency_aname.TextMarginBottom = 0;
            this.txt_currency_aname.TextMarginLeft = 3;
            this.txt_currency_aname.TextMarginTop = 0;
            this.txt_currency_aname.TextPlaceholder = "";
            this.txt_currency_aname.UseSystemPasswordChar = false;
            this.txt_currency_aname.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.label3.Location = new System.Drawing.Point(596, 237);
            this.label3.Name = "label3";
            this.label3.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.label3.Size = new System.Drawing.Size(52, 29);
            this.label3.TabIndex = 2;
            this.label3.Text = "الفكة";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.label1.Location = new System.Drawing.Point(605, 137);
            this.label1.Name = "label1";
            this.label1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.label1.Size = new System.Drawing.Size(43, 29);
            this.label1.TabIndex = 2;
            this.label1.Text = "الرمز";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.label2.Location = new System.Drawing.Point(591, 187);
            this.label2.Name = "label2";
            this.label2.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.label2.Size = new System.Drawing.Size(57, 29);
            this.label2.TabIndex = 2;
            this.label2.Text = "الصرف";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.label6.Location = new System.Drawing.Point(548, 90);
            this.label6.Name = "label6";
            this.label6.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.label6.Size = new System.Drawing.Size(100, 29);
            this.label6.TabIndex = 2;
            this.label6.Text = "الاسم الاتيني";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.label5.Location = new System.Drawing.Point(558, 40);
            this.label5.Name = "label5";
            this.label5.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.label5.Size = new System.Drawing.Size(90, 29);
            this.label5.TabIndex = 2;
            this.label5.Text = "أسم العملة";
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.BorderRadius = 1;
            this.bunifuShadowPanel3.BorderThickness = 1;
            this.bunifuShadowPanel3.Controls.Add(this.btn_new);
            this.bunifuShadowPanel3.Controls.Add(this.btn_Save);
            this.bunifuShadowPanel3.Controls.Add(this.btn_Edit);
            this.bunifuShadowPanel3.Controls.Add(this.btn_delete);
            this.bunifuShadowPanel3.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuShadowPanel3.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel3.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(0, 586);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowDepth = 5;
            this.bunifuShadowPanel3.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(858, 98);
            this.bunifuShadowPanel3.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel3.TabIndex = 19;
            // 
            // btn_new
            // 
            this.btn_new.AllowAnimations = true;
            this.btn_new.AllowMouseEffects = true;
            this.btn_new.AllowToggling = false;
            this.btn_new.AnimationSpeed = 200;
            this.btn_new.AutoGenerateColors = false;
            this.btn_new.AutoRoundBorders = false;
            this.btn_new.AutoSizeLeftIcon = true;
            this.btn_new.AutoSizeRightIcon = true;
            this.btn_new.BackColor = System.Drawing.Color.Transparent;
            this.btn_new.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_new.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_new.BackgroundImage")));
            this.btn_new.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.ButtonText = "جديد";
            this.btn_new.ButtonTextMarginLeft = 0;
            this.btn_new.ColorContrastOnClick = 45;
            this.btn_new.ColorContrastOnHover = 45;
            this.btn_new.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_new.CustomizableEdges = borderEdges1;
            this.btn_new.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_new.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_new.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_new.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_new.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_new.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.btn_new.ForeColor = System.Drawing.Color.White;
            this.btn_new.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_new.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_new.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_new.IconMarginLeft = 11;
            this.btn_new.IconPadding = 10;
            this.btn_new.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_new.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_new.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_new.IconSize = 25;
            this.btn_new.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_new.IdleBorderRadius = 20;
            this.btn_new.IdleBorderThickness = 1;
            this.btn_new.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_new.IdleIconLeftImage = null;
            this.btn_new.IdleIconRightImage = null;
            this.btn_new.IndicateFocus = false;
            this.btn_new.Location = new System.Drawing.Point(635, 34);
            this.btn_new.Name = "btn_new";
            this.btn_new.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_new.OnDisabledState.BorderRadius = 20;
            this.btn_new.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.OnDisabledState.BorderThickness = 1;
            this.btn_new.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_new.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_new.OnDisabledState.IconLeftImage = null;
            this.btn_new.OnDisabledState.IconRightImage = null;
            this.btn_new.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_new.onHoverState.BorderRadius = 20;
            this.btn_new.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.onHoverState.BorderThickness = 1;
            this.btn_new.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_new.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_new.onHoverState.IconLeftImage = null;
            this.btn_new.onHoverState.IconRightImage = null;
            this.btn_new.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_new.OnIdleState.BorderRadius = 20;
            this.btn_new.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.OnIdleState.BorderThickness = 1;
            this.btn_new.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_new.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_new.OnIdleState.IconLeftImage = null;
            this.btn_new.OnIdleState.IconRightImage = null;
            this.btn_new.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_new.OnPressedState.BorderRadius = 20;
            this.btn_new.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_new.OnPressedState.BorderThickness = 1;
            this.btn_new.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_new.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_new.OnPressedState.IconLeftImage = null;
            this.btn_new.OnPressedState.IconRightImage = null;
            this.btn_new.Size = new System.Drawing.Size(150, 39);
            this.btn_new.TabIndex = 0;
            this.btn_new.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_new.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_new.TextMarginLeft = 0;
            this.btn_new.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_new.UseDefaultRadiusAndThickness = true;
            this.btn_new.Click += new System.EventHandler(this.btn_new_Click);
            // 
            // btn_Save
            // 
            this.btn_Save.AllowAnimations = true;
            this.btn_Save.AllowMouseEffects = true;
            this.btn_Save.AllowToggling = false;
            this.btn_Save.AnimationSpeed = 200;
            this.btn_Save.AutoGenerateColors = false;
            this.btn_Save.AutoRoundBorders = false;
            this.btn_Save.AutoSizeLeftIcon = true;
            this.btn_Save.AutoSizeRightIcon = true;
            this.btn_Save.BackColor = System.Drawing.Color.Transparent;
            this.btn_Save.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_Save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Save.BackgroundImage")));
            this.btn_Save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.ButtonText = "حفظ";
            this.btn_Save.ButtonTextMarginLeft = 0;
            this.btn_Save.ColorContrastOnClick = 45;
            this.btn_Save.ColorContrastOnHover = 45;
            this.btn_Save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_Save.CustomizableEdges = borderEdges2;
            this.btn_Save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Save.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Save.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Save.Enabled = false;
            this.btn_Save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Save.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Save.ForeColor = System.Drawing.Color.White;
            this.btn_Save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Save.IconMarginLeft = 11;
            this.btn_Save.IconPadding = 10;
            this.btn_Save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Save.IconSize = 25;
            this.btn_Save.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_Save.IdleBorderRadius = 20;
            this.btn_Save.IdleBorderThickness = 1;
            this.btn_Save.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_Save.IdleIconLeftImage = null;
            this.btn_Save.IdleIconRightImage = null;
            this.btn_Save.IndicateFocus = false;
            this.btn_Save.Location = new System.Drawing.Point(429, 34);
            this.btn_Save.Name = "btn_Save";
            this.btn_Save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Save.OnDisabledState.BorderRadius = 20;
            this.btn_Save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.OnDisabledState.BorderThickness = 1;
            this.btn_Save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Save.OnDisabledState.IconLeftImage = null;
            this.btn_Save.OnDisabledState.IconRightImage = null;
            this.btn_Save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Save.onHoverState.BorderRadius = 20;
            this.btn_Save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.onHoverState.BorderThickness = 1;
            this.btn_Save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Save.onHoverState.IconLeftImage = null;
            this.btn_Save.onHoverState.IconRightImage = null;
            this.btn_Save.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_Save.OnIdleState.BorderRadius = 20;
            this.btn_Save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.OnIdleState.BorderThickness = 1;
            this.btn_Save.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_Save.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Save.OnIdleState.IconLeftImage = null;
            this.btn_Save.OnIdleState.IconRightImage = null;
            this.btn_Save.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Save.OnPressedState.BorderRadius = 20;
            this.btn_Save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Save.OnPressedState.BorderThickness = 1;
            this.btn_Save.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Save.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Save.OnPressedState.IconLeftImage = null;
            this.btn_Save.OnPressedState.IconRightImage = null;
            this.btn_Save.Size = new System.Drawing.Size(150, 39);
            this.btn_Save.TabIndex = 8;
            this.btn_Save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Save.TextMarginLeft = 0;
            this.btn_Save.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_Save.UseDefaultRadiusAndThickness = true;
            this.btn_Save.Click += new System.EventHandler(this.btn_Save_Click);
            // 
            // btn_Edit
            // 
            this.btn_Edit.AllowAnimations = true;
            this.btn_Edit.AllowMouseEffects = true;
            this.btn_Edit.AllowToggling = false;
            this.btn_Edit.AnimationSpeed = 200;
            this.btn_Edit.AutoGenerateColors = false;
            this.btn_Edit.AutoRoundBorders = false;
            this.btn_Edit.AutoSizeLeftIcon = true;
            this.btn_Edit.AutoSizeRightIcon = true;
            this.btn_Edit.BackColor = System.Drawing.Color.Transparent;
            this.btn_Edit.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Edit.BackgroundImage")));
            this.btn_Edit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.ButtonText = "تعديل";
            this.btn_Edit.ButtonTextMarginLeft = 0;
            this.btn_Edit.ColorContrastOnClick = 45;
            this.btn_Edit.ColorContrastOnHover = 45;
            this.btn_Edit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_Edit.CustomizableEdges = borderEdges3;
            this.btn_Edit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Edit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Edit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Edit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Edit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Edit.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.btn_Edit.ForeColor = System.Drawing.Color.White;
            this.btn_Edit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Edit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Edit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Edit.IconMarginLeft = 11;
            this.btn_Edit.IconPadding = 10;
            this.btn_Edit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Edit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Edit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Edit.IconSize = 25;
            this.btn_Edit.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.IdleBorderRadius = 20;
            this.btn_Edit.IdleBorderThickness = 1;
            this.btn_Edit.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.IdleIconLeftImage = null;
            this.btn_Edit.IdleIconRightImage = null;
            this.btn_Edit.IndicateFocus = false;
            this.btn_Edit.Location = new System.Drawing.Point(223, 34);
            this.btn_Edit.Name = "btn_Edit";
            this.btn_Edit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Edit.OnDisabledState.BorderRadius = 20;
            this.btn_Edit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.OnDisabledState.BorderThickness = 1;
            this.btn_Edit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Edit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Edit.OnDisabledState.IconLeftImage = null;
            this.btn_Edit.OnDisabledState.IconRightImage = null;
            this.btn_Edit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Edit.onHoverState.BorderRadius = 20;
            this.btn_Edit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.onHoverState.BorderThickness = 1;
            this.btn_Edit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Edit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Edit.onHoverState.IconLeftImage = null;
            this.btn_Edit.onHoverState.IconRightImage = null;
            this.btn_Edit.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.OnIdleState.BorderRadius = 20;
            this.btn_Edit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.OnIdleState.BorderThickness = 1;
            this.btn_Edit.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_Edit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Edit.OnIdleState.IconLeftImage = null;
            this.btn_Edit.OnIdleState.IconRightImage = null;
            this.btn_Edit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Edit.OnPressedState.BorderRadius = 20;
            this.btn_Edit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Edit.OnPressedState.BorderThickness = 1;
            this.btn_Edit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Edit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Edit.OnPressedState.IconLeftImage = null;
            this.btn_Edit.OnPressedState.IconRightImage = null;
            this.btn_Edit.Size = new System.Drawing.Size(150, 39);
            this.btn_Edit.TabIndex = 9;
            this.btn_Edit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Edit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Edit.TextMarginLeft = 0;
            this.btn_Edit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_Edit.UseDefaultRadiusAndThickness = true;
            this.btn_Edit.Click += new System.EventHandler(this.btn_Edit_Click);
            // 
            // btn_delete
            // 
            this.btn_delete.AllowAnimations = true;
            this.btn_delete.AllowMouseEffects = true;
            this.btn_delete.AllowToggling = false;
            this.btn_delete.AnimationSpeed = 200;
            this.btn_delete.AutoGenerateColors = false;
            this.btn_delete.AutoRoundBorders = false;
            this.btn_delete.AutoSizeLeftIcon = true;
            this.btn_delete.AutoSizeRightIcon = true;
            this.btn_delete.BackColor = System.Drawing.Color.Transparent;
            this.btn_delete.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_delete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_delete.BackgroundImage")));
            this.btn_delete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.ButtonText = "حذف";
            this.btn_delete.ButtonTextMarginLeft = 0;
            this.btn_delete.ColorContrastOnClick = 45;
            this.btn_delete.ColorContrastOnHover = 45;
            this.btn_delete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_delete.CustomizableEdges = borderEdges4;
            this.btn_delete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_delete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_delete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_delete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_delete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_delete.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            this.btn_delete.ForeColor = System.Drawing.Color.White;
            this.btn_delete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_delete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_delete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_delete.IconMarginLeft = 11;
            this.btn_delete.IconPadding = 10;
            this.btn_delete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_delete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_delete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_delete.IconSize = 25;
            this.btn_delete.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_delete.IdleBorderRadius = 20;
            this.btn_delete.IdleBorderThickness = 1;
            this.btn_delete.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_delete.IdleIconLeftImage = null;
            this.btn_delete.IdleIconRightImage = null;
            this.btn_delete.IndicateFocus = false;
            this.btn_delete.Location = new System.Drawing.Point(17, 34);
            this.btn_delete.Name = "btn_delete";
            this.btn_delete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_delete.OnDisabledState.BorderRadius = 20;
            this.btn_delete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnDisabledState.BorderThickness = 1;
            this.btn_delete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_delete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_delete.OnDisabledState.IconLeftImage = null;
            this.btn_delete.OnDisabledState.IconRightImage = null;
            this.btn_delete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_delete.onHoverState.BorderRadius = 20;
            this.btn_delete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.onHoverState.BorderThickness = 1;
            this.btn_delete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_delete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.onHoverState.IconLeftImage = null;
            this.btn_delete.onHoverState.IconRightImage = null;
            this.btn_delete.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_delete.OnIdleState.BorderRadius = 20;
            this.btn_delete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnIdleState.BorderThickness = 1;
            this.btn_delete.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_delete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.OnIdleState.IconLeftImage = null;
            this.btn_delete.OnIdleState.IconRightImage = null;
            this.btn_delete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_delete.OnPressedState.BorderRadius = 20;
            this.btn_delete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_delete.OnPressedState.BorderThickness = 1;
            this.btn_delete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_delete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_delete.OnPressedState.IconLeftImage = null;
            this.btn_delete.OnPressedState.IconRightImage = null;
            this.btn_delete.Size = new System.Drawing.Size(150, 39);
            this.btn_delete.TabIndex = 10;
            this.btn_delete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_delete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_delete.TextMarginLeft = 0;
            this.btn_delete.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_delete.UseDefaultRadiusAndThickness = true;
            this.btn_delete.Click += new System.EventHandler(this.btn_delete_Click);
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.dgv_currency);
            this.panel1.Controls.Add(this.bunifuShadowPanel4);
            this.panel1.Controls.Add(this.bunifuShadowPanel3);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(858, 684);
            this.panel1.TabIndex = 20;
            // 
            // dgv_currency
            // 
            this.dgv_currency.AllowUserToAddRows = false;
            this.dgv_currency.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.dgv_currency.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgv_currency.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv_currency.BackgroundColor = System.Drawing.Color.White;
            this.dgv_currency.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgv_currency.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.dgv_currency.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Gray;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Cairo", 9F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.Gray;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgv_currency.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgv_currency.ColumnHeadersHeight = 40;
            this.dgv_currency.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.CurrencyIDColumn,
            this.CurrencyNameColumn});
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Cairo Medium", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgv_currency.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgv_currency.DoubleBuffered = true;
            this.dgv_currency.EnableHeadersVisualStyles = false;
            this.dgv_currency.GridColor = System.Drawing.Color.WhiteSmoke;
            this.dgv_currency.HeaderBgColor = System.Drawing.Color.Gray;
            this.dgv_currency.HeaderForeColor = System.Drawing.Color.White;
            this.dgv_currency.Location = new System.Drawing.Point(96, 23);
            this.dgv_currency.Name = "dgv_currency";
            this.dgv_currency.ReadOnly = true;
            this.dgv_currency.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.dgv_currency.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.dgv_currency.RowHeadersVisible = false;
            this.dgv_currency.RowHeadersWidth = 51;
            this.dgv_currency.RowTemplate.DividerHeight = 1;
            this.dgv_currency.RowTemplate.Height = 30;
            this.dgv_currency.RowTemplate.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            this.dgv_currency.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv_currency.Size = new System.Drawing.Size(639, 199);
            this.dgv_currency.TabIndex = 26;
            this.dgv_currency.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_currency_CellDoubleClick);
            // 
            // CurrencyIDColumn
            // 
            this.CurrencyIDColumn.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.CurrencyIDColumn.HeaderText = "رقم العملة";
            this.CurrencyIDColumn.MinimumWidth = 6;
            this.CurrencyIDColumn.Name = "CurrencyIDColumn";
            this.CurrencyIDColumn.ReadOnly = true;
            this.CurrencyIDColumn.Width = 160;
            // 
            // CurrencyNameColumn
            // 
            this.CurrencyNameColumn.HeaderText = "اسم العملة";
            this.CurrencyNameColumn.MinimumWidth = 6;
            this.CurrencyNameColumn.Name = "CurrencyNameColumn";
            this.CurrencyNameColumn.ReadOnly = true;
            // 
            // frm_Currency
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(858, 684);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frm_Currency";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frm_Currency";
            this.bunifuShadowPanel4.ResumeLayout(false);
            this.bunifuShadowPanel4.PerformLayout();
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgv_currency)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel4;
        private Bunifu.UI.WinForms.BunifuTextBox txt_currency_aname;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_new;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Save;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Edit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_delete;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuTextBox txt_currency_ename;
        private Bunifu.Framework.UI.BunifuCustomDataGrid dgv_currency;
        private System.Windows.Forms.RadioButton rb_foreigner_currency;
        private System.Windows.Forms.RadioButton rb_local_currency;
        private Bunifu.UI.WinForms.BunifuTextBox txt_currency_symbol;
        private Bunifu.UI.WinForms.BunifuTextBox txt_currency_decent;
        private Bunifu.UI.WinForms.BunifuTextBox txt_currency_exchange;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.DataGridViewTextBoxColumn CurrencyIDColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn CurrencyNameColumn;
    }
}